package com.markdownreader.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7CF8E0)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4B635C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8DF)
val md_theme_light_onSecondaryContainer = Color(0xFF07201A)
val md_theme_light_background = Color(0xFFFCFCFC)
val md_theme_light_onBackground = Color(0xFF1F1F1F)
val md_theme_light_surface = Color(0xFFFCFCFC)
val md_theme_light_onSurface = Color(0xFF1F1F1F)
val md_theme_light_surfaceVariant = Color(0xFFF0EBE6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4945)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF5DDBC4)
val md_theme_dark_onPrimary = Color(0xFF003830)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF7CF8E0)
val md_theme_dark_secondary = Color(0xFFB1CCC3)
val md_theme_dark_onSecondary = Color(0xFF1D352F)
val md_theme_dark_secondaryContainer = Color(0xFF334B45)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8DF)
val md_theme_dark_background = Color(0xFF18181B)
val md_theme_dark_onBackground = Color(0xFFE0E0E0)
val md_theme_dark_surface = Color(0xFF18181B)
val md_theme_dark_onSurface = Color(0xFFE0E0E0)
val md_theme_dark_surfaceVariant = Color(0xFF2C2C2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)

// Sepia theme colors
val md_theme_sepia_primary = Color(0xFF5D4037)
val md_theme_sepia_onPrimary = Color(0xFFFFFFFF)
val md_theme_sepia_primaryContainer = Color(0xFFEFEBE3)
val md_theme_sepia_onPrimaryContainer = Color(0xFF3E2723)
val md_theme_sepia_secondary = Color(0xFF795548)
val md_theme_sepia_onSecondary = Color(0xFFFFFFFF)
val md_theme_sepia_secondaryContainer = Color(0xFFD7CCC8)
val md_theme_sepia_onSecondaryContainer = Color(0xFF3E2723)
val md_theme_sepia_background = Color(0xFFF4ECD8)
val md_theme_sepia_onBackground = Color(0xFF3E2723)
val md_theme_sepia_surface = Color(0xFFF4ECD8)
val md_theme_sepia_onSurface = Color(0xFF3E2723)
val md_theme_sepia_surfaceVariant = Color(0xFFE7DAC1)
val md_theme_sepia_onSurfaceVariant = Color(0xFF4E342E)
val md_theme_sepia_error = Color(0xFFBA1A1A)
val md_theme_sepia_onError = Color(0xFFFFFFFF)
